# Generated by Django 3.1.5 on 2021-02-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='appnauser',
        ),
    ]
