# Generated by Django 3.1.5 on 2021-05-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210207_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_created_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
