# Generated by Django 3.1.6 on 2021-05-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_account_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('Index', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Catagory', models.CharField(max_length=122)),
                ('Product_Sub_Catagory', models.CharField(max_length=122)),
                ('Product_Name', models.CharField(max_length=256)),
                ('Brand', models.CharField(max_length=122)),
                ('Retail_Price', models.IntegerField()),
                ('Description', models.CharField(max_length=2546)),
                ('Image_1', models.CharField(max_length=256)),
                ('Image_2', models.CharField(max_length=256)),
                ('Image_3', models.CharField(max_length=256)),
            ],
        ),
    ]
