# Generated by Django 3.1.5 on 2021-06-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210531_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_jason', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=40)),
                ('fname_pay', models.CharField(max_length=122)),
                ('lname_pay', models.CharField(max_length=122)),
                ('email_pay', models.CharField(max_length=122)),
                ('address_pay', models.CharField(max_length=122)),
                ('city_pay', models.CharField(max_length=122)),
                ('state_pay', models.CharField(max_length=122)),
                ('zipcode_pay', models.CharField(max_length=122)),
                ('phone_pay', models.CharField(default='0000000000', max_length=122)),
            ],
        ),
    ]
